import { COLOR_TOKENS } from './color';
import { GRAY_SCALE_TOKENS } from './grayScale';
export const TAG_TOKENS = {
  text: {
    gray: GRAY_SCALE_TOKENS.gray11,
    mauve: COLOR_TOKENS.mauve11,
    slate: COLOR_TOKENS.slate11,
    sage: COLOR_TOKENS.sage11,
    olive: COLOR_TOKENS.olive11,
    sand: COLOR_TOKENS.sand11,
    tomato: COLOR_TOKENS.tomato11,
    red: COLOR_TOKENS.red11,
    ruby: COLOR_TOKENS.ruby11,
    crimson: COLOR_TOKENS.crimson11,
    pink: COLOR_TOKENS.pink11,
    plum: COLOR_TOKENS.plum11,
    purple: COLOR_TOKENS.purple11,
    violet: COLOR_TOKENS.violet11,
    iris: COLOR_TOKENS.iris11,
    cyan: COLOR_TOKENS.cyan11,
    turquoise: COLOR_TOKENS.turquoise11,
    sky: COLOR_TOKENS.sky11,
    blue: COLOR_TOKENS.blue11,
    jade: COLOR_TOKENS.jade11,
    green: COLOR_TOKENS.green11,
    grass: COLOR_TOKENS.grass11,
    mint: COLOR_TOKENS.mint11,
    lime: COLOR_TOKENS.lime11,
    bronze: COLOR_TOKENS.bronze11,
    gold: COLOR_TOKENS.gold11,
    brown: COLOR_TOKENS.brown11,
    orange: COLOR_TOKENS.orange11,
    amber: COLOR_TOKENS.amber11,
    yellow: COLOR_TOKENS.yellow11,
  },
  // Step 4 gives a visible tint; orange, amber, yellow and lime are already
  // strongly tinted at step 3.
  background: {
    gray: GRAY_SCALE_TOKENS.gray4,
    mauve: COLOR_TOKENS.mauve4,
    slate: COLOR_TOKENS.slate4,
    sage: COLOR_TOKENS.sage4,
    olive: COLOR_TOKENS.olive4,
    sand: COLOR_TOKENS.sand4,
    tomato: COLOR_TOKENS.tomato4,
    red: COLOR_TOKENS.red4,
    ruby: COLOR_TOKENS.ruby4,
    crimson: COLOR_TOKENS.crimson4,
    pink: COLOR_TOKENS.pink4,
    plum: COLOR_TOKENS.plum4,
    purple: COLOR_TOKENS.purple4,
    violet: COLOR_TOKENS.violet4,
    iris: COLOR_TOKENS.iris4,
    cyan: COLOR_TOKENS.cyan4,
    turquoise: COLOR_TOKENS.turquoise4,
    sky: COLOR_TOKENS.sky4,
    blue: COLOR_TOKENS.blue4,
    jade: COLOR_TOKENS.jade4,
    green: COLOR_TOKENS.green4,
    grass: COLOR_TOKENS.grass4,
    mint: COLOR_TOKENS.mint4,
    lime: COLOR_TOKENS.lime3,
    bronze: COLOR_TOKENS.bronze4,
    gold: COLOR_TOKENS.gold4,
    brown: COLOR_TOKENS.brown4,
    orange: COLOR_TOKENS.orange3,
    amber: COLOR_TOKENS.amber3,
    yellow: COLOR_TOKENS.yellow3,
  },
  // Steps 6-7 sit between the tint and the solid, enough to outline a pill on white.
  border: {
    gray: GRAY_SCALE_TOKENS.gray6,
    mauve: COLOR_TOKENS.mauve6,
    slate: COLOR_TOKENS.slate6,
    sage: COLOR_TOKENS.sage6,
    olive: COLOR_TOKENS.olive6,
    sand: COLOR_TOKENS.sand6,
    tomato: COLOR_TOKENS.tomato6,
    red: COLOR_TOKENS.red6,
    ruby: COLOR_TOKENS.ruby6,
    crimson: COLOR_TOKENS.crimson6,
    pink: COLOR_TOKENS.pink6,
    plum: COLOR_TOKENS.plum6,
    purple: COLOR_TOKENS.purple6,
    violet: COLOR_TOKENS.violet6,
    iris: COLOR_TOKENS.iris6,
    cyan: COLOR_TOKENS.cyan6,
    turquoise: COLOR_TOKENS.turquoise6,
    sky: COLOR_TOKENS.sky6,
    blue: COLOR_TOKENS.blue6,
    jade: COLOR_TOKENS.jade6,
    green: COLOR_TOKENS.green6,
    grass: COLOR_TOKENS.grass6,
    mint: COLOR_TOKENS.mint6,
    lime: COLOR_TOKENS.lime7,
    bronze: COLOR_TOKENS.bronze6,
    gold: COLOR_TOKENS.gold6,
    brown: COLOR_TOKENS.brown6,
    orange: COLOR_TOKENS.orange7,
    amber: COLOR_TOKENS.amber7,
    yellow: COLOR_TOKENS.yellow7,
  },
};
